import apiClient from "@/api/apiClient";

type ChapterApi = {
  id: string;
  title?: string;
  name?: string;
};

type QuestionApi = {
  id: string;
  content: string;
  questionFormat: string;
  chapterId?: string;
};
export interface TestItem {
  id: string;
  title: string;
  testType: "QUIZ" | "ESSAY";
  scope: "CHAPTER" | "SUBJECT" | "COURSE";
  isAutoGenerated: boolean;
  durationMinutes: number;
  startTime: string | null;
  endTime: string | null;
  maxAttempts: number;
  createdAt: string;
  submissionCount: number;
  questionCount: number;
  chapterId: string | null;
  chapterTitle: string | null;
}

export interface SubmissionItem {
  id: string;
  status: "PENDING" | "GRADED";
  score: number | null;
  submittedAt: string;
  finalScoreStatus: string | null;
  student: {
    id: string;
    firstName: string;
    lastName: string;
    middleName: string | null;
    email: string;
    avatarUrl: string | null;
  };
  userAnswers?: { essayAnswer: string | null }[];
}

export interface GenerationRule {
  difficulty: string;
  totalCount: number;
}

export interface CreateTestPayload {
  title: string;
  testType: "QUIZ" | "ESSAY";
  durationMinutes: number;
  startTime?: string | null;
  endTime?: string | null;
  maxAttempts: number;
  isAutoGenerated: boolean;
  questionIds: string[];

  rule?: {
    easy?: number;
    medium?: number;
    hard?: number;
  };

  scope?: "CHAPTER" | "SUBJECT" | "COURSE";
  chapterId?: string;
  subjectId?: string;
  courseId?: string;

}

export interface UpdateTestPayload {
  title?: string;
  durationMinutes?: number;
  startTime?: string | null;
  endTime?: string | null;
  maxAttempts?: number;
}

export interface ChapterItem {
  id: string;
  title: string;
}

export interface QuestionBankItem {
  id: string;
  content: string;
  questionFormat: string;
  typeId?: string;
  chapterId?: string;
}

const withMockFallback = async <T>(
  apiCall: () => Promise<T>,
  fallback: () => T,
): Promise<T> => {
  try {
    return await apiCall();
  } catch {
    return fallback();
  }
};

// Mock tests theo đề bài
const mockTests: TestItem[] = [
  {
    id: "t-1",
    title: "Quiz chương 1: Giới thiệu",
    testType: "QUIZ",
    scope: "CHAPTER",
    isAutoGenerated: false,
    durationMinutes: 30,
    startTime: null,
    endTime: null,
    maxAttempts: 2,
    createdAt: new Date().toISOString(),
    submissionCount: 5,
    questionCount: 10,
    chapterId: "ch-1",
    chapterTitle: "Chương 1",
  },
  {
    id: "t-2",
    title: "ASM cuối môn: Báo cáo dự án",
    testType: "ESSAY",
    scope: "SUBJECT",
    isAutoGenerated: false,
    durationMinutes: 0,
    startTime: "2025-12-01T08:00:00.000Z",
    endTime: "2025-12-15T23:59:00.000Z",
    maxAttempts: 1,
    createdAt: new Date().toISOString(),
    submissionCount: 3,
    questionCount: 1,
    chapterId: null,
    chapterTitle: null,
  },
  {
    id: "t-3",
    title: "Thi giữa kỳ (Random)",
    testType: "QUIZ",
    scope: "SUBJECT",
    isAutoGenerated: true,
    durationMinutes: 45,
    startTime: "2025-11-20T08:00:00.000Z",
    endTime: "2025-11-20T10:00:00.000Z",
    maxAttempts: 1,
    createdAt: new Date().toISOString(),
    submissionCount: 12,
    questionCount: 20,
    chapterId: null,
    chapterTitle: null,
  },
];

const mockSubmissions: SubmissionItem[] = [
  {
    id: "sub-1",
    status: "PENDING",
    score: null,
    submittedAt: new Date().toISOString(),
    finalScoreStatus: "MANUAL_PENDING",
    student: {
      id: "stu-1",
      firstName: "An",
      lastName: "Nguyễn",
      middleName: null,
      email: "an.nguyen@example.com",
      avatarUrl: null,
    },
    userAnswers: [
      { essayAnswer: "Bài làm của em về kiến trúc hệ thống LMS..." },
    ],
  },
  {
    id: "sub-2",
    status: "GRADED",
    score: 8.5,
    submittedAt: new Date().toISOString(),
    finalScoreStatus: "MANUAL_GRADED",
    student: {
      id: "stu-2",
      firstName: "Bình",
      lastName: "Trần",
      middleName: "Văn",
      email: "binh.tran@example.com",
      avatarUrl: null,
    },
    userAnswers: [{ essayAnswer: "Phân tích mô hình MVC và ứng dụng..." }],
  },
  {
    id: "sub-3",
    status: "PENDING",
    score: null,
    submittedAt: new Date().toISOString(),
    finalScoreStatus: "MANUAL_PENDING",
    student: {
      id: "stu-3",
      firstName: "Chi",
      lastName: "Lê",
      middleName: null,
      email: "chi.le@example.com",
      avatarUrl: null,
    },
    userAnswers: [
      { essayAnswer: "Em trình bày use-case và sequence diagram..." },
    ],
  },
];

export const subjectTestsService = {
  async getTeacherSubjectTests(subjectId: string): Promise<TestItem[]> {
    return withMockFallback(
      async () => {
        const response = await apiClient.get(
          `/v1/subjects/${subjectId}/tests`,
        );
        return response?.data?.data || [];
      },
      () => mockTests,
    );
  },

  async getSubjectChapters(subjectId: string): Promise<ChapterItem[]> {
    return withMockFallback(
      async () => {
        const response = await apiClient.get(
          `/v1/subjects/${subjectId}/chapters`,
        );

        const data = response?.data?.data || [];

        return data.map((c: ChapterApi) => ({
          id: c.id,
          title: c.title || c.name || "",
        }));
      },
      () => [
        { id: "ch-1", title: "Chương 1: Tổng quan" },
        { id: "ch-2", title: "Chương 2: React cơ bản" },
      ],
    );
  },

  async getSubjectQuestions(
    subjectId: string,
    chapterId?: string,
  ): Promise<QuestionBankItem[]> {
    return withMockFallback(
      async () => {
        const response = await apiClient.get(`/v1/questions`, {
          params: {
            subjectId,
            chapterId: chapterId || undefined,
            page: 1,
            pageSize: 1000, // ✅ lấy hết câu hỏi
          },
        });

        console.log("RAW FIXED API:", response.data);

        const items: QuestionApi[] = response?.data?.data?.items || [];

        return items.map((q) => ({
          id: q.id,
          content: q.content,
          questionFormat: q.questionFormat,
          chapterId: q.chapterId,
        }));
      },
      () => [],
    );
  },

  async createChapterTest(chapterId: string, payload: CreateTestPayload) {
    return apiClient.post(`/v1/chapters/${chapterId}/tests`, payload);
  },

  async createSubjectTest(subjectId: string, payload: CreateTestPayload) {
    return apiClient.post(`/v1/subjects/${subjectId}/tests`, payload);
  },

  async createCourseTest(courseId: string, payload: CreateTestPayload) {
    return apiClient.post(`/v1/courses/${courseId}/tests`, payload);
  },
  async generateTest(payload: CreateTestPayload) {
    return apiClient.post(`/v1/tests/generate`, payload);
  },

  async updateTest(testId: string, payload: UpdateTestPayload) {
    return apiClient.put(`/v1/tests/${testId}`, payload);
  },

  async deleteTest(testId: string) {
    return apiClient.delete(`/v1/tests/${testId}`);
  },

  async getTestSubmissions(testId: string): Promise<SubmissionItem[]> {
    return withMockFallback(
      async () => {
        const response = await apiClient.get(`/v1/tests/${testId}/submissions`);
        return response?.data?.data || [];
      },
      () => mockSubmissions,
    );
  },

  async gradeAssignmentSubmission(
    submissionId: string,
    payload: {
      score: number;
      teacherFeedback?: string;
      feedbackFileUrl?: string;
    },
  ): Promise<SubmissionItem> {
    return withMockFallback(
      async () => {
        const response = await apiClient.post(
          `/v1/assignments/${submissionId}/grade`,
          payload,
        );
        return response?.data?.data;
      },
      () => ({
        ...mockSubmissions[0],
        id: submissionId,
        status: "GRADED",
        score: payload.score,
        finalScoreStatus: "MANUAL_GRADED",
      }),
    );
  },
};
